# Generated by Django 3.2.4 on 2021-06-05 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='budget',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlybudget',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.appuser'),
            preserve_default=False,
        ),
    ]
