# Generated by Django 3.2.4 on 2021-06-30 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20210605_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='year',
            field=models.IntegerField(default=1970, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
