# Generated by Django 3.2.4 on 2021-07-19 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20210630_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='purchased_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 16, 54, 11, 424628)),
            preserve_default=False,
        ),
    ]
